### ISSUE TITLE
Map Explorer UI: Map configuration missing trigger error

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/liverpool16#46]
If there is a conf with no Map, code should not raise any error and should plot the chart only. Take FTS.json as example

**Comment by alexandru-m-g** [comment]
@danmihaila after looking a bit into this I think this is actually more like a new feature. It's not enough for the browser to not raise an exception. Because there's no legend for this chart we won't be able to remove it
We would need to decide:
* [ ] how do we remove the chart ? Do we show it on the legend (which until now was showing only layers) ?
* [ ] How do we decide what colors it uses ? Do we add new configuration that can specify the colors of a chart ? Until now it was computed based on the colors of the corresponding map layer.

**Comment by danmihaila** [comment]
@alexandru-m-g I think the comment from Yumi is answering to your first 
https://github.com/OCHA-DAP/liverpool16/issues/57#issuecomment-216877833

**Comment by alexandru-m-g** [comment]
@danmihaila Thanks. It seems like what exactly we should show in the legend for a slice of data with no layer is not yet decided. Also we need to still decide how we go about the 2nd question.

**Comment by danmihaila** [comment]
Based on Yumi's comments and Alex's comments we decided:
- [ ] keep the "maps" configuration with: type (chart-only), colors and maybe threshold fields
- [ ] display one long color for legend together with threshold option (max chart value)
- [ ] Rename Map Layer to Data Layer
- [ ]

**Comment by alexandru-m-g** [comment]
@danmihaila after the latest commit:
1.  No need for threshold
2.  Displays one long color ( but no numbers / thresholds - we would need a refactoring for that since chart values are not accessible at that time )
3.  Done
