### ISSUE TITLE
ME: 4 layers is still possible! 

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/liverpool16#79]
![screen shot 2016-05-10 at 18 13 53](https://cloud.githubusercontent.com/assets/3865844/15151710/09283b64-16db-11e6-8f74-a79ae10a1202.png)

**Comment by aalecs** [comment]
This is happening because the chart doesn't have a map layer so it isn't assigned to a map layer type.
So we can have 4 charts at the same time: 3 related to layer types (choropleth/bubble/point) and one that's not related to any.
Adding to the M.E. another slice that only contains a chart will replace the current slice (green one) and it's chart.
