### ISSUE TITLE
The Map Explorer pages should be responsive and usable on mobile devices

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/liverpool16#9]

**Comment by baripembo** [comment]
- [ ] The charts area needs to have a separate solution for mobile. I think having a open/collapse panel for it at the bottom of the screen is a good solution. For readability on mobile portrait view, the chart should ideally span the full width of the screen. If there is more than one chart maybe the user could swipe to see the next chart.

- [ ] Need to discuss if there is any functionality that can/should be simplified for mobile. For example, the interaction between map and charts for a mobile user

- [ ] Info tooltip that now appears on hover on desktop needs to be implemented as a click event for any touch device (we can use js detection such as Modernizr)

- [ ] Once the design is applied to the prototype, we will need to test on target devices to make sure everything looks good

**Comment by davidmegginson** [comment]
Another suggestion — what about a small (icon-sized) version of the chart in a corner somewhere, that zooms to fill the screen when the user taps on it? That gives users an idea of what's available and guides them to take the right action.

When the chart zooms up, the map could shrink to icon size, so that the user knows how to get back.

(It would also be good to track the state (panel open/closed or icon zoomed/unzoomed) in the URL hash, so that someone can bookmark or share a link to the view that they want, but that's a separate feature request.)

**Comment by SimonbJohnson** [comment]
The filters on the chart need to be taken into consideration.  A chart can filter what is seen on the map and in desktop view the filter is visible to the user at all times.  If the chart is removed from view there needs to be an indicator that the chart is still applying a filter

**Comment by danmihaila** [comment]
@baripembo I think this issue can be closed for the moment.
